name: ri
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.9.0
  - aiosignal=1.2.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.2
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.11.17
  - cachetools=4.2.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.2.0
  - cryptography=41.0.3
  - cycler=0.11.0
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - flatbuffers=2.0.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.22.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - h5py=3.9.0
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - jedi=0.19.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.4
  - munkres=1.1.4
  - nest-asyncio=1.5.8
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=23.1
  - pandas=2.1.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.41
  - protobuf=3.20.3
  - psutil=5.9.5
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.17.2
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pywin32=306
  - pyzmq=25.1.1
  - re2=2022.04.01
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - seaborn=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - urllib3=1.26.18
  - vc=14.2
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wcwidth=0.2.12
  - werkzeug=2.2.3
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - wrapt=1.14.1
  - xz=5.4.2
  - yarl=1.9.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
